language: python
python:
  - "3.3"

matrix:
  include:
  - env: BACKEND=mysql SPHINX_VERSION=2.2.6
  - env: BACKEND=mysql SPHINX_VERSION=2.2.10
  - env: BACKEND=postgres SPHINX_VERSION=2.2.6
  - env: BACKEND=postgres SPHINX_VERSION=2.2.10

install:
  - sudo bash -c "$(curl -fsSL https://gist.githubusercontent.com/jorgecarleitao/ee5cede492dbe41be8a5/raw/install_sphinx.sh)" ${SPHINX_VERSION}
  - pip install .
  - pip install django psycopg2 pymysql
  - pip install coveralls

script:
  - PYTHONPATH=$PYTHONPATH:`pwd` coverage run `which django-admin.py` test --settings=tests.settings_travis tests

after_success: coveralls
