language: python
python:
  - "3.4"

env:
  - DJANGO_VERSION=1.8 BACKEND=mysql SPHINX_VERSION=2.2.10
  - DJANGO_VERSION=1.8 BACKEND=mysql SPHINX_VERSION=2.2.11
  - DJANGO_VERSION=1.8 BACKEND=psycopg2 SPHINX_VERSION=2.2.10
  - DJANGO_VERSION=1.8 BACKEND=psycopg2 SPHINX_VERSION=2.2.11
  - DJANGO_VERSION=1.10 BACKEND=mysql SPHINX_VERSION=2.2.10
  - DJANGO_VERSION=1.10 BACKEND=mysql SPHINX_VERSION=2.2.11
  - DJANGO_VERSION=1.10 BACKEND=psycopg2 SPHINX_VERSION=2.2.10
  - DJANGO_VERSION=1.10 BACKEND=psycopg2 SPHINX_VERSION=2.2.11

install:
  - sudo bash -c "$(curl -fsSL https://gist.githubusercontent.com/jorgecarleitao/ee5cede492dbe41be8a5/raw/install_sphinx.sh)" ${SPHINX_VERSION}
  - pip install .
  - pip install PyMySQL psycopg2
  - pip install django==$DJANGO_VERSION
  - pip install coveralls

script:
  - PYTHONPATH=$PYTHONPATH:`pwd` coverage run `which django-admin.py` test --settings=tests.settings_travis tests

after_success: coveralls
