language: python
python:
  - "3.3"

env:
  - BACKEND=mysql
  - BACKEND=postgres

install:
  - sudo bash -c "$(curl -fsSL https://gist.githubusercontent.com/jorgecarleitao/ee5cede492dbe41be8a5/raw/install_sphinx.sh)" 2.2.6
  - pip install .
  - pip install django psycopg2 pymysql

script:
  - PYTHONPATH=$PYTHONPATH:`pwd` django-admin.py test --settings=tests.settings_travis tests
